config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/contato', to: 'contact#form', as: :contact_form
  post '/destino', to: 'contact#destine', as: :destiny
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def form
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/_myform.html.erb
<%= form_with(url: destiny_path) do |f| %>
    <%= f.label("como devemos te chamar?", for:"name") %>
    <%= f.text_field("name", id: "name") %>

    <%= f.label("qual o seu email?", for: "email") %>
    <%= f.email_field("email", id: "email") %>
    
    <%= f.label("telefone", for:"tel") %>
    <%= f.telephone_field("tel", id: "tel")  %>
    
    <%= f.label("mensagem?", for:"message") %>
    <%= f.text_area("message", id: "message") %>

    <%= f.button("Enviar", type:"submit") %>
<% end %>

app/views/contact/destine.html.erb
<h2>destino</h2>

app/views/contact/form.html.erb
<h2>Comece agora!</h2>
<%= render 'myform' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dia2Manha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>